# Generated by Django 6.0.1 on 2026-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='color_tone',
            field=models.CharField(choices=[('yellow-orange', 'Yellow Orange'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red'), ('blue', 'Blue'), ('purple', 'Purple'), ('teal', 'Teal'), ('light-purple', 'Light Purple'), ('light-blue', 'Light Blue'), ('green', 'Green'), ('black', 'Black'), ('muted-gray', 'Muted Gray'), ('brown', 'Brown'), ('light-pink', 'Light Pink'), ('kiwi', 'Kiwi'), ('rose', 'Rose')], default='blue', help_text='Color theme for the subject card and pages.', max_length=20),
        ),
    ]
